language: python
dist: xenial

python:
  - "3.6"
  - "3.7"
  - "3.8"
  # TODO add 3.9
  - "3.9-dev"

install: pip install tox-travis tox tox-venv

# Used by the `test` stage.
script: tox

stages:
  - test
  - lint

jobs:
  allow_failures:
    - python: "3.9-dev"

  include:

    # The `test` stage using the `python` matrix defined above
    # is included implicitly.

    - stage: lint
      name: "Code Linting"
      python: "3.7"
      script: TOXENV=lint tox

    - stage: check-docs
      name: "Docs check"
      python: "3.7"
      script: TOXENV=check-docs tox
